# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:12

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          name: Restore NPM Cache
          key: npm-cache-{{ checksum "package.json" }}

      - run:
          name: Install npm dependencies
          command: npm install

      - save_cache:
          name: Save NPM Cache
          key: npm-cache-{{ checksum "package.json" }}
          paths:
            - 'node_modules'

      - run:
          name: Run Linting
          command: npm run lint

  deploy_prod:
    machine:
      enabled: true
    steps:
      - run:
          name: SSH - Installed build dependencies dependencies
          command: |
            ssh $SSH_USER@$SSH_HOST "sudo apt-get install -y jq moreutils"

      - run:
          name: SSH - Remove previous copy of the repo if present
          halt_build_on_fail: false
          command: |
            ssh $SSH_USER@$SSH_HOST "rm ~/zencrepes_zapi/ -R"

      - run:
          name: SSH - Clone Repo locally
          command: |
            ssh $SSH_USER@$SSH_HOST "git clone https://github.com/zencrepes/zapi.git ~/zencrepes_zapi/"

      - run:
          name: SSH - Build Docker image
          no_output_timeout: 320m
          command: |
            ssh $SSH_USER@$SSH_HOST "cd ~/zencrepes_zapi/; docker build -t zencrepes/zapi ."

      - run:
          name: SSH - Run docker-compose down
          halt_build_on_fail: false
          command: |
            ssh $SSH_USER@$SSH_HOST "cd ~/zencrepes_zapi/; docker-compose -f docker-compose.yml down"

      - run:
          name: SSH - Run docker-compose up
          command: |
            ssh $SSH_USER@$SSH_HOST 'cd ~/zencrepes_zapi/; docker-compose -f docker-compose.yml up -d '

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy_prod:
          requires:
            - build
          filters:
            branches:
              only: master
